### ISSUE TITLE
Boss bars are displayed even when EntityFlag.FLAG_DONT_COUNT_BOSS_HP is set to true

### ISSUE THREAD

**Issue by Volensia** [wofsauge/Enhanced-Boss-Bars#23]
Hey there, I'm the developer for the mod "Delirium Fix" and I use the EntityFlag "FLAG_DONT_COUNT_BOSS_HP" to hide the extra boss bars during the Delirium fight. It looks like this without the Enhanced Boss Bars mod:
![image](https://github.com/wofsauge/Enhanced-Boss-Bars/assets/14161817/e5b54b87-c9da-4a3d-893f-85688a8d0d14)

However, when the Enhanced Boss Bars mod is installed, it looks like this:
![image](https://github.com/wofsauge/Enhanced-Boss-Bars/assets/14161817/43101218-cec4-4e4b-8c9b-e9bdfea26a51)

I believe this is a bug because a boss with the flag FLAG_DONT_COUNT_BOSS_HP is supposed to hide the boss bar.

In order to fix this bug, you just have to change line 322 of main.lua to
```if (entity:IsBoss() and not HPBars:evaluateEntityIgnore(entity) or bossEntry) and not entity:HasEntityFlags(EntityFlag.FLAG_DONT_COUNT_BOSS_HP) then```

And everything should look normal, like this:
![image](https://github.com/wofsauge/Enhanced-Boss-Bars/assets/14161817/8573d7f7-128b-41f1-8b7e-4bfbdb9deee0)

**Comment by wofsauge** [comment]
Thanks for the report. the bug should be fixed now :)
