### ISSUE TITLE
Boss Bars during the Mega Satan fight

### ISSUE THREAD

**Issue by profmori** [wofsauge/Enhanced-Boss-Bars#9]
During the mega satan fight other spawned bosses, such as the sins, horsemen and angels all have health bars, even if the mega satan health bar has been disabled.

Also, mega satan 2 health bar shows up, even if the mega satan health bar is disabled, which definitely should not occur.

**Comment by wofsauge** [comment]
Thanks for the report. I fixed both issues now with commit 3f4cddf7abde556737e0b51cea982a07d8c13c74.
